name: Convert flashcards.md to flashcards.apkg v2

on:
  workflow_dispatch:

jobs:
 publish:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - uses: actions/md2apkg-action@v0.0.0
