name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  job_CI:
    name: CI Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: step-git-checkout
        uses: actions/checkout@v3
      - name: step-use-node-LTS
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: step-run-npm-commands
        run: |
          npm ci
          npm run build
      - name: step-upload-artifacts
        uses: actions/upload-artifact@v3
        id: upload
        with:
          path: |
            build
            !build/**.md
      - name: step-download-artifacts
        uses: actions/download-artifact@v3
        id: download
        with:
          path: build
      - name: step-echo-download-path
        run: echo ${{steps.download.outputs.download-path}}